{% extends "layout.phtml" %}

{% block left %}
<div class="col-sm-3 col-xs-12 step step-1">
    <div class="card dark">
        <div class="card-header">
            CircleBilling installation
        </div>

        <div class="card-body">
            <p>This setup will guide you through installation process of CircleBilling.</p>
            <p>Check if your system meets minimum requirements to install and run billing software.</p>
        </div>
    </div>
</div>

<div class="col-sm-3 col-xs-12 step step-2">
    <div class="card dark">
        <div class="card-header">
            Database configuration
        </div>

        <div class="card-body">
            <p>CircleBilling stores data in SQL database. You should already have an existing database before this step. If you do not have database prepared, you should do that now.</p>
            <p>Installer will create all required tables in your database after correct connection details are provided.</p>
            <h4 class="pt10">How to create database?</h4>
            <p>Depending on your hosting provider database can be created in different ways.</p>
            <p>Best way is to check the documentation available with your webhosting account. You can contact their support if you really get stuck.</p>
        </div>
    </div>
</div>

<div class="col-sm-3 col-xs-12 step step-3">
    <div class="card dark">
        <div class="card-header">
            Administrator account
        </div>

        <div class="card-body">
            <p>This is the main user account to control all aspects of CircleBilling.</p>
            <p>Email will be used to login to admin area.</p>
            <p>Make sure password is strong.</p>
        </div>
    </div>

    <div class="spacer-20"></div>

    <div class="card dark">
        <div class="card-header">Well done! </div>

        <div class="card-body">
            <p>Thank you for choosing CircleBilling</p>
            <a href="{{ live_site }}" title="" class="btnIconLeft mr10 mt10" target="_blank"><img src="{{resource_url}}images/user.png" alt="" class="icon"><span>Client area</span></a>
            <a href="{{ admin_site }}" title="" class="btnIconLeft mr10 mt10" target="_blank"><img src="{{resource_url}}images/adminUser.png" alt="" class="icon"><span>Admin area</span></a>
        </div>
    </div>
</div>
{% endblock %}


{% block content %}
        <form action="" class="mainForm" method="get" id="installer" data-step="1">
            <fieldset>
                <div class="widget">
                    <div class="wizard">
                        <div class="step" id="step-1">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead class="thead-dark">
                                    <tr>
                                        <th scope="col">Requirement</th>
                                        <th scope="col">Status</th>
                                        <th scope="col">&nbsp;</th>
                                    </tr>
                                    </thead>

                                    <tbody>
                                    <tr>
                                        <td>Operating system</td>
                                        <td><strong class="{{ os_ok ? 'green' : 'red'}}">{{ os }}</strong></td>
                                        <td>{% if not os_ok %}CircleBilling might not work properly on your operating system{% endif %}</td>
                                    </tr>

                                    <tr>
                                        <td>PHP version</td>
                                        <td><strong class="{{ php_ver_ok ? 'green' : 'red'}}">{{ php_ver }}</strong></td>
                                        <td>{% if not php_ver_ok %}Required PHP version >{{ php_ver_req }}{% endif %}</td>
                                    </tr>

                                    <tr>
                                        <td>PHP Safe mode</td>
                                        <td><strong class="{{ php_safe_mode ? 'red' : 'green'}}">{{ php_safe_mode ? 'ON' : 'OFF'}}</strong></td>
                                        <td>{% if php_safe_mode %}PHP safe mode should be OFF{% endif %}</td>
                                    </tr>

                                    {% for ext,loaded in extensions %}
                                    <tr>
                                        <td>PHP Extension: <strong>{{ ext }}</strong></td>
                                        <td><strong class="{{ loaded ? 'green' : 'red'}}">{{ loaded ? 'Ok' : 'Fail'}}</strong></td>
                                        <td>{% if not loaded %}Contact your server administrator to enable <strong>PHP {{ ext }} extension</strong>{% endif %}</td>
                                    </tr>
                                    {% endfor %}

                                    {% for file,writable in files %}
                                    <tr>
                                        <td>{{ file }}</td>
                                        <td><strong class="{{ writable ? 'green' : 'red'}}">{{ writable ? 'Yes' : 'No'}}</strong></td>
                                        <td>{% if not writable %}Please make sure that file exists and is writable.{%endif%}</td>
                                    </tr>
                                    {% endfor %}

                                    {% for folder,writable in folders %}
                                    <tr>
                                        <td>{{ folder }}</td>
                                        <td><strong class="{{ writable ? 'green' : 'red'}}">{{ writable ? 'Yes' : 'No'}}</strong></td>
                                        <td>{% if not writable %}Please make sure that directory exists and is writable.{%endif%}</td>
                                    </tr>
                                    {% endfor %}

                                    </tbody>
                                </table>
                            </div>

                            {% if tos %}
                                <div class="card dark">
                                    <div class="card-header">
                                        Terms of service:
                                    </div>

                                    <div class="card-body">
                                        <div class="form-group form-check">
                                            <input class="form-check-input" id="agree" type="checkbox" name="agree" value="1"{% if agree %} checked="checked"{% endif %}/>
                                            <label class="form-check-label" for="exampleCheck1">{{ tos }}</label>
                                        </div>
                                    </div>
                                </div>
                            {% endif %}
                        </div>

                        <div class="step" id="step-2">
                            <div class="card dark">
                                <div class="card-header">
                                    Database Configuration
                                </div>

                                <div class="card-body">
                                    <div class="form-group">
                                        <label>Database hostname:</label>
                                        <input class="form-control" type="text" id="db_host" name="db_host" value="{{ db_host|default('localhost') }}" required="required" placeholder="localhost"/>
                                        <small class="form-text text-muted">Enter the database hostname or ip address. Example: 127.0.0.1 or localhost.</small>
                                    </div>

                                    <div class="form-group">
                                        <label>Database name:</label>
                                        {{ request.db_name|default('sdfsdf') }}
                                        <input class="form-control" type="text" id="db_name" name="db_name" value="{{ request.db_name|default(db_name) }}" required="required" placeholder="circlebilling"/>
                                        <small class="form-text text-muted">Here we need to know you database name where we should create the tables.</small>
                                    </div>

                                    <div class="form-group">
                                        <label>Database user:</label>
                                        <input class="form-control" type="text" id="db_user" name="db_user" value="{{ request.db_user|default(db_user) }}" required="required" placeholder="username"/>
                                        <small class="form-text text-muted">The user should have enough rights to create tables, insert, select and delete entries.</small>
                                    </div>

                                    <div class="form-group">
                                        <label>Database password:</label>
                                        <input class="form-control" type="password" id="db_pass" name="db_pass" value="{{ request.db_pass|default(db_pass) }}" placeholder="******"/>
                                        <small class="form-text text-muted">Enter your users password, it should be very strong.</small>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="step" id="step-3">
                            <div class="card dark">
                                <div class="card-header">
                                    Administrator configuration
                                </div>

                                <div class="card-body">
                                    <div class="form-group">
                                        <label>Administrator name:</label>
                                        <input class="form-control" type="text" name="admin_name" id="admin_name" value="{{ request.admin_name|default(admin_name) }}" autocomplete="off" required="required" placeholder="Administrator Name"/>
                                        <small class="form-text text-muted">Enter your first name and last name for the administrator account. Example: John Doe</small>
                                    </div>

                                    <div class="form-group">
                                        <label>Email:</label>
                                        <input class="form-control" type="text" name="admin_email" id="admin_email" value="{{ request.admin_email|default(admin_email) }}" autocomplete="off" required="required" placeholder="admin@yourdomain.com"/>
                                        <small class="form-text text-muted">Enter the email for your main administrator account.</small>
                                    </div>

                                    <div class="form-group">
                                        <label>Password:</label>
                                        <input class="form-control" type="password" name="admin_pass" id="admin_pass" value="{{ request.admin_pass|default(admin_pass) }}" autocomplete="off" required="required" placeholder="Administrator password"/>
                                        <small class="form-text text-muted">Enter the password for your main administrator account.</small>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="step" id="step-4">
                            <div class="body">
                                <h1>Congratulations! CircleBilling was successfully installed.</h1>

                                <p>Even though CircleBilling was installed successfully you must take a few more actions.</p>

                                <h2>1. Remove installation module</h2>
                                <p>Remove installation module for security reasons.</p>
                                <pre>{{ install_module_path }}</pre>

                                <h2>2. Change configuration file permissions</h2>
                                <p>Change configuration file permissions to read-only (CHMOD 644)</p>
                                <pre>{{ config_file_path }}</pre>

                                <h2>3. Setup cron job</h2>
                                <p>Setup this cron job to run every five minutes</p>
                                <pre>*/5 * * * * php {{ cron_path }}</pre>
                                
                                <h2>4. Disable directory listing with .htaccess</h2>
                                <p>Disable directory listing with .htaccess</p>
                                <pre>Rename file htaccess.txt to .htaccess</pre>
                            </div>
                        </div>

                        <div class="spacer-20"></div>

                        <div class="card dark wizard-footer">
                            <div class="card-body">
                                <div class="clearfix">
                                    <button class="btn btn-secondary btn-prev-step float-md-left" type="button">Back</button>
                                    <button class="btn btn-dark btn-next-step float-md-right" type="button">Continue</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="fix"></div>
                </div>
            </fieldset>
        </form>
{% endblock %}

{% block js %}
<div id="overlay" style="position: absolute; display: none; z-index: 1000; background-color: whitesmoke; width: 725px; height: 50px; opacity:0.5;"></div>
<script src="{{resource_url}}js/installer.js" type="text/javascript"></script>
<script type="text/javascript">

    jQuery(document).ready(function() {
        cb.installer.init({
            installUrl: '{{constant("SYSTEM_URL_INSTALL")}}',
            //loadingOverlay: jQuery('#overlay'), --default
        });
    });
    
</script>
{% endblock %}