<div class="mb10">
    <a href="http://http://docs.circlebilling.com/" title="" target="_blank">{% trans 'Help' %}</a>
    <a href="https://www.forum.circlebilling.com/" title="" target="_blank">{% trans 'Forum' %}</a>
    <a href="https://github.com/CircleBilling/CircleBilling/issues" title="" target="_blank">{% trans 'Report bug' %}</a>
</div>
<div>
    &copy; {{ now|date('Y') }}. All rights reserved.
    <a href="https://www.circlebilling.com/" title="Billing system" target="_blank">CircleBilling {{ guest.system_version }}</a>
</div>