{% extends request.ajax ? "layout_blank.phtml" : "layout_default.phtml" %}

{% import "macro_functions.phtml" as mf %}

{% block meta_title %}{% trans 'Contact us' %}{% endblock %}
{% block breadcrumb %}{% trans 'Contact us' %}{% endblock %}

{% block content %}
    {% set company = guest.system_company %}
    <div class="row mt-5">
        <div class="col-md-12 text-center">
            <h1>{% trans 'Contact us' %}</h1>
            <p>{{ company.signature }}</p>
        </div>
    </div>

    <div class="row mt-5">
        <div class="col-md-4 ml-auto mr-auto">
            <div class="card dark">

                <div class="card-header">
                    {% trans 'Contact us' %}
                </div>

                <div class="card-body">
                    <form method="post" action="" id="public-ticket-create" class="form form-horizontal span6">
                        <div class="form-group">
                            <label>{% trans 'Name' %}: </label>
                            <input class="form-control" type="text" name="name" value="{{request.name}}" required="required" id="name">
                        </div>

                        <div class="form-group">
                            <label>{% trans 'Email' %}: </label>
                            <input class="form-control" type="email" name="email" value="{{request.email}}" required="required" id="email">
                        </div>


                        <div class="form-group">
                            <label>{% trans 'Subject' %}: </label>
                            <input class="form-control" type="text" name="subject" value="{{request.subject}}" required="required" id="subject">
                        </div>

                        <div class="form-group">
                            <label>{% trans 'Message' %}: </label>
                            <textarea class="form-control" name="message" cols="5" rows="5" required="required" id="message">{{request.message}}</textarea>
                        </div>


                        {{ mf.recaptcha }}
                        <div class="form-group">
                            <button class="btn btn-info btn-large pull-right" type="submit" value="{% trans 'Send' %}" data-loading-text="Loading...">{% trans 'Send' %}</button>
                        </div>


                        </fieldset>

                        <input type="hidden" name="anti-spam" value="1" id="anti-spam" required="required"/>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="row mt-5">
        <div class="col-md-4 ml-auto mr-auto">
            <div class="card dark">

                <div class="card-header">
                    {% trans 'Contact us' %}
                </div>

                <div class="card-body">
                    <strong>
                        <dl class="span3 offset1">
                            <dd>
                                {{ company.name }}
                            </dd>
                            <dd>
                                {{ company.address_1 }}
                            </dd>
                            <dd>
                                {{ company.address_2 }}
                            </dd>
                            <dd>
                                {{ company.address_3 }}
                            </dd>
                            <dd>
                                {{ company.tel }}
                            </dd>
                            <dd>
                                {{ company.www }}
                            </dd>
                            <dd>
                                {{ company.email }}
                            </dd>
                        </dl>
                    </strong>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script type="text/javascript">
        jQuery(document).ready(function() {
            jQuery('#anti-spam').remove();

            jQuery('#public-ticket-create').bind('submit',function(){
                jQuery('.wait').show();

                CB.APP.Post(
                    'guest/support/ticket_create',
                    jQuery(this).serialize(),
                    function(result) {
                        CB.APP.Redirect('{{ 'support/contact-us/conversation'|link }}' + '/' + result);
                    }
                );
                return false;
            });
        });
    </script>
{% endblock %}
