{% extends request.ajax ? "layout_blank.phtml" : "layout_default.phtml" %}

{% import "macro_functions.phtml" as mf %}

{% block meta_title %}{{ticket.subject}}{% endblock %}

{% block breadcrumb %}
    <li><a href="{{ 'support' | link}}">{% trans 'Support tickets' %}</a></li>
    <li class="divider">/</li>
    {{ticket.subject}}
{% endblock %}

{% block content %}

    <div class="row mt-5">
        <div class="col-md-12 text-center">
            <h1>{% trans 'Support Ticket: '%} {{ticket.subject}}</h1>
            <p>Ticket number <i>#{{ ticket.id }}</i> for department <i>{{ticket.helpdesk.name}}</i></p>

            {% if ticket.status != 'closed' %}
                <button class="btn btn-small api-button" data-api-url="client/support/ticket_close" data-api-data='{"id" : "{{ ticket.id}}" }' data-api-reload="1"> {% trans 'Close ticket' %}</button>
            {% endif %}
        </div>
    </div>

    <div class="row mt-5">

        <div class="col-md-7 col-xs-12">
            <div class="card dark">
                <div class="card-header">
                    {% trans 'Ticket information' %}
                </div>

                <div class="card-body">
                    <ul class="chat">
                        {% for i, message in ticket.messages %}
                            <li class="left clearfix">
                                <span class="chat-img float-left">
                                    <img src="{{ message.author.email|gravatar }}?size=60" alt="{{ message.author.name }}" class="img-circle" />
                                </span>

                                <div class="chat-body clearfix">
                                    <div class="header">
                                        <strong class="primary-font">{{ message.author.name }}</strong>
                                        <small class="float-right text-muted">
                                            <span class="glyphicon glyphicon-time"></span>#{{ i+1 }} | {{ message.created_at|bb_date }}
                                        </small>
                                    </div>
                                    <p>
                                        {{ message.content|bbmd }}
                                    </p>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>

            <div class="card dark mt-5">
                <div class="card-header">
                    {% trans 'Ticket Answer' %}
                </div>

                <div class="card-body">
                    {% if ticket.status != 'closed' %}
                        <form method="post" action="" class="api-form" data-api-url="{{ 'api/client/support/ticket_reply'|link }}" data-api-reload="1">
                            <input type="hidden" name="id" value="{{ ticket.id }}">

                            <div class="form-group">
                                <label>{% trans 'Your message:' %}</label>
                                <textarea name="content" cols="5" rows="6" class="form-control" required="required" id="ticket-reply-text"></textarea>
                            </div>

                            <button class="btn btn-info btn-large text-right" type="submit" id="submit-support-message" value="{% trans 'Post' %}" onclick="">{% trans 'Send' %}</button>
                        </form>
                    {% elseif ticket.status == 'closed' %}
                        <div class="alert alert-white text-center">{% trans 'Ticket was closed and cannot be reopened.' %}</div>
                    {% endif %}
                </div>
            </div>
        </div>



        <div class="col-md-5 col-xs-12">

            <div class="col-md-12">
                <div class="card dark">
                    <div class="card-header">
                        {% trans 'Ticket information' %}

                        {#% if ticket.status != 'closed' %}
                            <div class="data-header-actions">
                                <button class="btn btn-small" type="button" id="ticket-close">{% trans 'Close ticket' %}</button>
                            </div>
                        {% endif #}
                    </div>

                    <div class="card-body">
                        <div class="table-responsive">
                            <table cellpadding="0" cellspacing="0" width="100%" class="table">
                                <tr>
                                    <td>{% trans 'Ticket ID' %}</td>
                                    <td><b>#{{ticket.id}}</b></td>
                                </tr>

                                <tr>
                                    <td>{% trans 'Help desk' %}</td>
                                    <td>{{ticket.helpdesk.name}}</td>
                                </tr>

                                <tr>
                                    <td>{% trans 'Status' %}</td>
                                    <td><div class="label {% if ticket.status=='open'%}label-success{% elseif ticket.status == 'on_hold'%}label-warning{%endif%}">{{mf.status_name(ticket.status)}}</div></td>
                                </tr>

                                <tr>
                                    <td>{% trans 'Time opened' %}</td>
                                    <td>{{ticket.created_at|bb_date }}</td>
                                </tr>

                                {% if ticket.rel_type == 'order' and ticket.rel_id %}
                                    <tr>
                                        <td>{% trans 'Related to' %}</td>
                                        <td><a href="{{ 'order/service/manage'|link }}/{{ ticket.rel_id }}">{% trans 'Service #' %} {{ ticket.rel_id }}</a></td>
                                    </tr>
                                {% endif %}
                            </table>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-12 col-xs-12 mt-5">
                <div class="card dark">
                    <div class="card-header">
                        {% trans 'Last tickets'%}
                    </div>

                    <div class="card-body">
                        <div class="table-responsive">
                            <table cellpadding="0" cellspacing="0" width="100%" class="table">
                                <thead>
                                <tr>
                                    <th>{% trans 'Subject' %}</th>
                                    <th>{% trans 'Help desk' %}</th>
                                    <th>{% trans 'Status' %}</th>
                                    <th>{% trans 'Submitted' %}</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% set tickets = client.support_ticket_get_list({"per_page":5, "page":request.page}) %}
                                {% for i, t in tickets.list %}
                                <tr {% if ticket.id == t.id %}class="alert alert-info"{% endif %}>
                                    <td><a href="{{ 'support/ticket'|link }}/{{t.id}}">{{t.subject|truncate(40)}}</a></td>
                                    <td>{{t.helpdesk.name}}</td>
                                    <td><span class="label {% if t.status=='open'%}label-info{% elseif t.status == 'on_hold'%}label-warning{%endif%}">{{mf.status_name(t.status)}}</span></td>
                                    <td>{{t.created_at|timeago}} {% trans 'ago' %}</td>
                                </tr>
                                {% else %}
                                <tr>
                                    <td colspan="5">{% trans 'The list is empty' %}</td>
                                </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>

                        <a class="btn btn-small" href="{{ '/support'|link }}">{% trans 'Back to tickets list' %}</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}