{% extends request.ajax ? "layout_blank.phtml" : "layout_default.phtml" %}

{% import "macro_functions.phtml" as mf %}

{% block meta_title %}{% trans 'Support tickets' %}{% endblock %}

{% block page_header %}{% trans 'Support tickets' %}{% endblock %}

{% block breadcrumb %}{% trans 'Support tickets' %}{% endblock %}

{% block content %}

    <div class="row mt-5">
        <div class="col-md-12 text-center">
            <h1>{% trans 'Support tickets'%}</h1>
            <p>{% trans 'Need an answer? We are here to help!' %}</p>
            <button class="btn btn-alt btn-info" id="buttonNewSupportTicket" data-toggle="modal" data-target="#modalNewSupportTicket">{% trans 'Submit new ticket' %}</button>
        </div>
    </div>

    <div class="row mt-5">
        <div class="col-md-6 col-xs-12 ml-auto mr-auto">
            <div class="card dark">
                <div class="card-header">
                    {% trans 'Your Support Requests' %}
                </div>

                <div class="card-body">
                    <div class="table-responsive">
                        <table cellpadding="0" cellspacing="0" width="100%" class="table">
                            <thead>
                                <tr>
                                    <th>{% trans 'Id' %}</th>
                                    <th>{% trans 'Subject' %}</th>
                                    <th>{% trans 'Help desk' %}</th>
                                    <th>{% trans 'Status' %}</th>
                                    <th>{% trans 'Submitted' %}</th>
                                    <th>{% trans 'Actions' %}</th>
                                </tr>
                            </thead>

                            <tbody>
                                {% set tickets = client.support_ticket_get_list({"per_page":10, "page":request.page}) %}
                                {% for i, ticket in tickets.list %}
                                    <tr>
                                        <td>#{{ticket.id}}</td>
                                        <td><a href="{{ 'support/ticket'|link }}/{{ticket.id}}">{{ticket.subject|truncate(40)}}</a></td>
                                        <td>{{ticket.helpdesk.name}}</td>
                                        <td><span class="label {% if ticket.status=='open'%}label-info{% elseif ticket.status == 'on_hold'%}label-warning{%endif%}">{{mf.status_name(ticket.status)}}</span></td>
                                        <td>{{ticket.created_at|timeago}} {% trans 'ago' %}</td>
                                        <td class="actions"><a href="{{ 'support/ticket'|link }}/{{ticket.id}}" class="btn btn-dark btn-small">{% if ticket.status=='closed'%}{% trans 'View' %}{% else %}{% trans 'Reply' %}{%endif%}</a></td>
                                    </tr>
                                {% else %}
                                    <tr>
                                        <td colspan="6">{% trans 'The list is empty' %}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>

                            {% if tickets.pages > 1 %}
                                <tfoot>
                                    <tr>
                                        <td colspan="6">
                                            {% include "partial_pagination.phtml" with {'list': tickets} %}
                                        </td>
                                    </tr>
                                </tfoot>
                            {% endif %}
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="modalNewSupportTicket" tabindex="-1" role="dialog" aria-labelledby="modalNewSupportTicketTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <form action="#" method="post" id="formNewTicket" class="form" style="background: none">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle">{% trans 'Submit new support ticket' %}</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>

                    <div class="modal-body">
                        <div class="form-group">
                            <label>{% trans 'Help desk' %}: </label>
                            {{ mf.selectbox('support_helpdesk_id', client.support_helpdesk_get_pairs, request.support_helpdesk_id, 1) }}
                        </div>

                        <div class="form-group">
                            <label>{% trans 'Subject' %}: </label>
                            <input type="text" name="subject" value="{{ request.subject|e }}" required="required" class="form-control"/>
                        </div>

                        <div class="form-group">
                            <label>{% trans 'Message' %}: </label>
                            <textarea name="content" cols="10" rows="6" required="required" class="form-control">{{ request.content|e }}</textarea>
                        </div>
                    </div>

                    <div class="modal-footer">
                        <button class="btn btn-dark btn-large" type="submit" value="{% trans 'Submit' %}">{% trans 'Submit' %}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}


{% block js %}
    <script type="text/javascript">
        jQuery(document).ready(function(){
            jQuery(document).on('submit', '#formNewTicket', function(){
                jQuery('.wait').show();
                CB.APP.Post(
                    'client/support/ticket_create',
                    $(this).serialize(),
                    function(result) {
                        CB.APP.Redirect('{{'support/ticket'|link }}' + '/' + result);
                    }
                );

               return false;
            });

            {% if request.ticket %}
                $('#modalNewSupportTicket').modal('show');
            {% endif %}
        });
    </script>
{% endblock %}