<!DOCTYPE html>
<!--[if IE 8]>    <html class="no-js ie8 ie" lang="en"> <![endif]-->
<!--[if IE 9]>    <html class="no-js ie9 ie" lang="en"> <![endif]-->
<!--[if gt IE 9]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <title>{% block meta_title %}{{ settings.meta_title }}{% endblock %}</title>

    <meta property="app:url" content="{{ constant('SYSTEM_URL') }}">
    <meta property="app:client_area" content="{{ '/'|link }}">

    <meta name="description" content="{% block meta_description %}{{ settings.meta_description }}{% endblock %}">
    <meta name="robots" content="{{ settings.meta_robots }}">
    <meta name="author" content="{{ settings.meta_author }}">
    <meta name="generator" content="CircleBilling {{ guest.system_version }}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% block opengraph %}{% endblock %}

    <link rel='stylesheet' type='text/css' href="{{ ('css/bootstrap.min.css') | asset_url }}">
    <link rel='stylesheet' type='text/css' href="{{ ('css/fontawesome-all.min.css') | asset_url }}">
    <link rel='stylesheet' type='text/css' href="{{ ('css/main.css') | asset_url }}">
    <link rel='stylesheet' type='text/css' href="{{ ('css/shema-' ~ settings.color_scheme ~ '.css') | asset_url }}">

    {% block head %}{% endblock %}
</head>
<body {% block body_attributes %}{% endblock %}>
    {% block body %}{% endblock %}

    {% include 'partial_pending_messages.phtml' ignore missing %}

    <script src="{{ 'js/jquery.min.js' | asset_url}}"></script>
    <script src="{{ 'js/popper.min.js' | asset_url}}"></script>
    <script src="{{ 'js/bootstrap.min.js' | asset_url}}"></script>
    <script src="{{ 'js/main.js' | asset_url}}"></script>
</body>
</html>