<!DOCTYPE html>
<html lang="en" class="h-100">
    <head>
        <meta charset="utf-8">
        <title>{% block meta_title %}{{ settings.meta_title }}{% endblock %}</title>

        <meta property="app:url" content="{{ constant('SYSTEM_URL') }}">
        <meta property="app:client_area" content="{{ '/'|link }}">

        <meta name="description" content="{% block meta_description %}{{ settings.meta_description }}{% endblock %}">
        <meta name="robots" content="{{ settings.meta_robots }}">
        <meta name="author" content="{{ settings.meta_author }}">
        <meta name="generator" content="BoxBilling {{ guest.system_version }}">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        {% block opengraph %}{% endblock %}

        <link rel='stylesheet' type='text/css' href="{{ ('css/bootstrap.min.css') | asset_url }}">
        <link rel='stylesheet' type='text/css' href="{{ ('css/fontawesome-all.min.css') | asset_url }}">
        <link rel='stylesheet' type='text/css' href="{{ ('css/main.css') | asset_url }}">
        <link rel='stylesheet' type='text/css' href="{{ ('css/shema-' ~ settings.color_scheme ~ '.css') | asset_url }}">

        {% block head %}{% endblock %}
    </head>

    <body class="d-flex flex-column h-100 {% block body_class %}{% endblock %}">

        {% if guest.extension_is_on({"mod":"cookieconsent"}) %}
            {% include 'mod_cookieconsent_index.phtml' ignore missing%}
        {% endif %}

        {% block body %}
            {% if client %}
                {% set profile = client.client_get %}
                {% set company = guest.system_company %}
                <header>
                    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                        <a class="navbar-brand" href="#">CircleBilling ClientArea</a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#adminMainNavbar" aria-controls="adminMainNavbar" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>

                        <div class="collapse navbar-collapse" id="adminMainNavbar">
                            {% include 'partial_menu.phtml' %}
                        </div>
                    </nav>

                    {% if settings.show_breadcrumb %}
                        {% block breadcrumbs %}
                            <nav aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li><a href="{{ '/'|link }}">{% trans 'Home' %}</a></li>

                                    <li class="divider">/</li>

                                    {% block breadcrumb %}
                                        <li class="active">{% trans 'Dashboard' %}</li>
                                    {% endblock %}
                                </ol>
                            </nav>
                        {% endblock %}
                    {% endif %}
                </header>

                <main class="container" role="main">
                    <div class="page-content">
                        {% if settings.show_page_header %}
                            {# block page_header %}
                                <article class="page-header">
                                    <h1>{{ block('meta_title') }}</h1>
                                    <p>{{ block('meta_description') }}</p>
                                </article>
                            {% endblock #}
                        {% endif %}

                        {% include "partial_message.phtml" %}

                        {% block content_before %}{% endblock %}
                        {% block content %}{% endblock %}
                        {% block content_after %}{% endblock %}
                    </div>

                    <div id="push"></div>
                </main>


                {% if settings.footer_enabled %}
                    <footer class="footer mt-auto py-3">

                        <div class="container text-center">
                            <span class="text-muted">&copy; {{ now|date('Y') }} {{ settings.footer_signature | default(company.signature) | raw }}. All rights reserved. Powered by <a href="http://www.circlebilling.com" title="Invoicing, billing and client management software" target="_blank">CircleBilling 1.0.0</a></span>
                        </div>

                        <ul>
                            {% if settings.footer_link_1_enabled %}
                            <li>
                                {% if 'http://' in settings.footer_link_1_page or  'https://' in settings.footer_link_1_page%}
                                <a href="{{ settings.footer_link_1_page }}">{{ settings.footer_link_1_title }}</a>
                                {% else %}
                                <a href="{{ settings.footer_link_1_page | link }}">{{ settings.footer_link_1_title }}</a>
                                {% endif %}
                            </li>
                            {% endif %}

                            {% if settings.footer_link_2_enabled %}
                            <li>
                                {% if 'http://' in settings.footer_link_2_page or  'https://' in settings.footer_link_2_page%}
                                <a href="{{ settings.footer_link_2_page }}">{{ settings.footer_link_2_title }}</a>
                                {% else %}
                                <a href="{{ settings.footer_link_2_page | link}}">{{ settings.footer_link_2_title }}</a>
                                {% endif %}
                            </li>
                            {% endif %}

                            {% if settings.footer_link_3_enabled %}
                            <li>
                                {% if 'http://' in settings.footer_link_3_page or  'https://' in settings.footer_link_3_page%}
                                <a href="{{ settings.footer_link_3_page }}">{{ settings.footer_link_3_title }}</a>
                                {% else %}
                                <a href="{{ settings.footer_link_3_page | link }}">{{ settings.footer_link_3_title }}</a>

                                {%endif %}
                            </li>
                            {% endif %}

                            {% if settings.footer_link_4_enabled %}
                            <li>
                                {% if 'http://' in settings.footer_link_4_page or  'https://' in settings.footer_link_4_page%}
                                <a href="{{ settings.footer_link_4_page }}">{{ settings.footer_link_4_title }}</a>
                                {% else %}
                                <a href="{{ settings.footer_link_4_page | link }}">{{ settings.footer_link_4_title }}</a>
                                {% endif %}
                            </li>
                            {% endif %}

                            {% if settings.footer_link_5_enabled %}
                            <li>
                                {% if 'http://' in settings.footer_link_5_page or  'https://' in settings.footer_link_5_page%}
                                <a href="{{ settings.footer_link_5_page }}">{{ settings.footer_link_5_title }}</a>
                                {% else %}
                                <a href="{{ settings.footer_link_5_page | link }}">{{ settings.footer_link_5_title }}</a>
                                {% endif %}
                            </li>
                            {% endif %}
                        </ul>

                        {% if settings.footer_to_top_enabled %}
                        <a href="#top" class="scrolltop"><span class="awe-arrow-up"></span></a>
                        {% endif %}
                    </footer>
                {% endif %}

                <div class="wait" style="display:none">
                    <div class="popup_block" style="position: fixed; top: 0; left: 0; width: 100%; height: 100%; background-color: #67676791;">
                        <img src="{{ 'images/loader.gif' | asset_url}}" style="position: relative; top: 40%; display: block; margin-left: auto; margin-right: auto; background-color: white; border: 8px solid #212529; padding: 30px;">
                    </div>
                </div>

                <noscript>NOTE: Many features on BoxBilling require Javascript and cookies. You can enable both via your browser's preference settings.</noscript>

            {% endif %}
        {% endblock %}

        {% if settings.inject_javascript %}
            {{ settings.inject_javascript | raw}}
        {% endif %}

        {% include 'partial_pending_messages.phtml' ignore missing %}

        <script src="{{ 'js/jquery.min.js' | asset_url}}"></script>
        <script src="{{ 'js/popper.min.js' | asset_url}}"></script>
        <script src="{{ 'js/bootstrap.min.js' | asset_url}}"></script>
        <script src="{{ 'js/main.js' | asset_url}}"></script>

        {% if not client %}
            <script type="text/javascript">
                CB.APP.Redirect('{{ "login"|link }}');
            </script>
        {% endif %}

        {% if settings.top_menu_order or settings.side_menu_order %}
        <script src="{{'orderbutton/js'| link({'options' : '1', 'width' : 600, 'theme_color' : 'green', 'background_color' : 'black', 'background_opacity' : 50, 'background_close' : 1, 'bind_selector' : '.order-button', 'border_radius' : 0, 'loader' : 8}) }}" ></script>
        {% endif %}

        {% block js %}{% endblock %}
    </body>
</html>