<ul class="navbar-nav mr-auto">
    {% if settings.side_menu_dashboard %}
        <li class="nav-item">
            <a class="nav-link" href="{{ '/'|link }}"><span class="awe-home"></span>{% trans 'Dashboard' %}</a>
        </li>
    {% endif %}

    {% if settings.side_menu_order %}
        <li class="nav-item">
            <a class="nav-link order-button" href="#"><span class="awe-shopping-cart"></span>{% trans 'Order' %}</a>
        </li>
    {% endif %}

    {% if settings.side_menu_services %}
        <li class="nav-item">
            <a class="nav-link" href="{{ '/order/service'|link }}"><span class="awe-cogs"></span>{% trans 'Services' %}</a>
        </li>
    {% endif %}

    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="dropdown-payment" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{% trans 'Payment' %}</a>
        <ul class="dropdown-menu" aria-labelledby="dropdown-payment">
            {% if settings.side_menu_invoices %}
                <li>
                    <a class="dropdown-item" href="{{ '/invoice'|link }}"><span class="awe-file-alt"></span>{% trans 'Invoices' %}</a>
                </li>
            {% endif %}

            {% if settings.side_menu_payments %}
            <li>
                <a class="dropdown-item" href="{{ '/client/balance'|link }}"><span class="awe-credit-card"></span>{% trans 'Payment history' %}</a>
            </li>
            {% endif %}
        </ul>
    </li>


    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="dropdown-support" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{% trans 'Support & Hilfe' %}</a>
        <ul class="dropdown-menu" aria-labelledby="dropdown-support">
            {% if settings.side_menu_support %}
                <li>
                    <a class="dropdown-item" href="{{ '/support'|link }}">Tickets</a>
                </li>
            {% endif %}

            {% if guest.extension_is_on({"mod":"news"}) %}
                <li>
                    <a class="dropdown-item" href="{{ '/news'|link }}">{% trans 'Blog' %}</a>
                </li>
            {% endif %}

            {% if guest.extension_is_on({"mod":"kb"}) %}
                <li>
                    <a class="dropdown-item" href="{{ '/kb'|link }}">{% trans 'Knowledge Base' %}</a>
                </li>
            {% endif %}

            {% if guest.extension_is_on({"mod":"forum"}) %}
                <li>
                    <a class="dropdown-item" href="{{ '/forum'|link }}">{% trans 'Forum' %}</a>
                </li>
            {% endif %}


        </ul>
    </li>
</ul>

<ul class="navbar-nav navbar-right">
    {% if settings.show_client_details %}
        <li class="nav-item dropdown user-profile">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown-clients" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{profile.first_name}} {{profile.last_name}}</a>

            <ul class="dropdown-menu" aria-labelledby="dropdown-clients">
                {% if settings.top_menu_profile %}
                    <li>
                        <a class="dropdown-item" href="{{ 'client/me'|link }}" title="{% trans 'Profile' %}">{% trans 'Profile' %}</a>
                    </li>
                {% endif %}

                {% if settings.side_menu_emails %}
                    <li>
                        <a class="dropdown-item" href="{{ '/email'|link }}">{% trans 'Emails' %}</a>
                    </li>
                {% endif %}


                {% if settings.top_menu_signout %}
                    <li>
                        <a class="dropdown-item" href="{{ 'client/logout' | link }}" title="{% trans 'Sign out' %}">{% trans 'Sign out' %}</a>
                    </li>
                {% endif %}

            </ul>
        </li>
    {% endif %}
</ul>