{% extends request.ajax ? "layout_blank.phtml" : "layout_default.phtml" %}

{% block meta_title %}
    {% trans 'Client Area' %}
{% endblock %}

{% block page_header %}
    {% trans 'Dashboard' %}
{% endblock %}

{% block breadcrumbs %}
    {% if not settings.hide_dashboard_breadcrumb %}
        <ul class="breadcrumb">
            <li><a href="{{ '/'|link }}">{% trans 'Home' %}</a></li>
            <li class="divider">/</li>
            <li class="active">{% trans 'Dashboard' %}</li>
        </ul>
    {% endif %}
{% endblock %}

{% import "macro_functions.phtml" as mf %}

{% block content %}

    {% if settings.showcase_enabled %}
        <div class="hero-unit">
            <h1>{{ settings.showcase_heading }}</h1>
            <p>{{ settings.showcase_text }}</p>
            <p><a class="btn btn-alt btn-primary btn-large" href="{{ settings.showcase_button_url }}">{{ settings.showcase_button_title }}</a></p>
        </div>
    {% endif %}

    {% if client %}

        {% set tickets = client.support_ticket_get_list({"status":'on_hold'}) %}
        {% if tickets.total > 0 %}
            <div class="row">
                <div class="col-md-12 col-xs-12 mt-5">
                    <div class="card dark">
                        <div class="card-header">
                            {% trans 'Tickets waiting your reply' %}
                        </div>

                        <div class="card-body">
                            <div class="table-responsive">
                                <table cellpadding="0" cellspacing="0" width="100%" class="table">
                                    <thead>
                                        <tr>
                                            <td>{% trans 'Id' %}</td>
                                            <td>{% trans 'Subject' %}</td>
                                            <td>{% trans 'Help desk' %}</td>
                                            <td>{% trans 'Status' %}</td>
                                            <td>{% trans 'Submitted' %}</td>
                                            <td>{% trans 'Actions' %}</td>
                                        </tr>
                                    </thead>

                                    <tbody>
                                        {% for i, ticket in tickets.list %}
                                            <tr class="{{ cycle(['odd', 'even'], i) }}">
                                                <td>{{ticket.id}}</td>
                                                <td><a href="{{ 'support/ticket'|link }}/{{ticket.id}}">{{ticket.subject}}</a></td>
                                                <td>{{ticket.helpdesk.name}}</td>
                                                <td><span class="label">{{mf.status_name(ticket.status)}}</span></td>
                                                <td>{{ticket.created_at|bb_date}}</td>
                                                <td><a href="{{ 'support/ticket'|link }}/{{ticket.id}}" class="btn btn-small btn-inverse">{% trans 'Reply' %}</a></td>
                                            </tr>
                                        {% else %}
                                            <tr>
                                                <td colspan="5">{% trans 'The list is empty' %}</td>
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}

        <div class="row mt-5">
            {% set profile = client.client_get %}
            <div class="col-md-3 col-xs-12">
                <div class="card dark">
                    <div class="card-header">
                        {% trans 'Profile' %}
                    </div>

                    <div class="card-body">
                        <div class="table-responsive">
                            <table cellpadding="0" cellspacing="0" width="100%" class="table">
                                <tbody>
                                    <tr>
                                        <td>{% trans 'ID' %}</td>
                                        <td>#{{ profile.id }}</td>
                                    </tr>
                                    <tr>
                                        <td>{% trans 'Email' %}</td>
                                        <td>{{ profile.email }}</td>
                                    </tr>
                                    <tr>
                                        <td>{% trans 'Balance' %}</td>
                                        <td>{{ profile.balance | money(profile.currency) }}</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>

                        <a class="btn btn-alt btn-inverse" href="{{ 'client/me'|link }}">{% trans 'Update' %}</a>
                    </div>
                </div>
            </div>


            <div class="col-md-3 col-xs-12">
                <div class="card dark">
                    <div class="card-header">
                        {% trans 'Invoices' %}
                    </div>

                    <div class="card-body">
                        <div class="table-responsive">
                            <table cellpadding="0" cellspacing="0" width="100%" class="table">
                                <tbody>
                                    <tr>
                                        <td>{% trans 'Total' %}</td>
                                        <td>#{{ client.invoice_get_list().total }}</td>
                                    </tr>
                                    <tr>
                                        <td>{% trans 'Paid' %}</td>
                                        <td>{{ client.invoice_get_list({"status":"paid"}).total }}</td>
                                    </tr>
                                    <tr>
                                        <td>{% trans 'Unpaid' %}</td>
                                        <td>{{ client.invoice_get_list({"status":"unpaid"}).total }}</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>

                        <a class="btn btn-alt btn-inverse" href="{{ 'invoice'|link }}">{% trans 'All Invoices' %}</a>
                    </div>
                </div>
            </div>

            <div class="col-md-3 col-xs-12">
                <div class="card dark">
                    <div class="card-header">
                        {% trans 'Orders' %}
                    </div>

                    <div class="card-body">
                        <div class="table-responsive">
                            <table cellpadding="0" cellspacing="0" width="100%" class="table">
                                <tbody>
                                <tr>
                                    <td>{% trans 'Total' %}</td>
                                    <td>#{{ client.order_get_list({"hide_addons":1}).total }}</td>
                                </tr>
                                <tr>
                                    <td>{% trans 'Active' %}</td>
                                    <td>{{ client.order_get_list({"hide_addons":1, "status":"active"}).total }}</td>
                                </tr>
                                <tr>
                                    <td>{% trans 'Expiring' %}</td>
                                    <td>{{ client.order_get_list({"expiring":1}).total }}</td>
                                </tr>
                                </tbody>
                            </table>
                        </div>

                        <a class="btn btn-alt btn-info order-button" href="{{ 'order'|link }}">{% trans 'New order' %}</a>
                        <a class="btn btn-alt btn-inverse" href="{{ 'order/service'|link }}">{% trans 'All orders' %}</a>
                    </div>
                </div>
            </div>

            <div class="col-md-3 col-xs-12">
                <div class="card dark">
                    <div class="card-header">
                        {% trans 'Tickets' %}</h2>
                    </div>

                    <div class="card-body">
                        <div class="table-responsive">
                            <table cellpadding="0" cellspacing="0" width="100%" class="table">
                                <tbody>
                                <tr>
                                    <td>{% trans 'Total' %}</td>
                                    <td>#{{ client.support_ticket_get_list().total }}</td>
                                </tr>
                                <tr>
                                    <td>{% trans 'Open' %}</td>
                                    <td>{{ client.support_ticket_get_list({"status":'open'}).total }}</td>
                                </tr>
                                <tr>
                                    <td>{% trans 'On Hold' %}</td>
                                    <td>{{ client.support_ticket_get_list({"status":'on_hold'}).total }}</td>
                                </tr>
                                </tbody>
                            </table>
                        </div>

                        <a class="btn btn-alt btn-info" href="{{ 'support'|link({'ticket' : 1}) }}">{% trans 'New ticket' %}</a>
                        <a class="btn btn-alt btn-inverse" href="{{ 'support'|link }}">{% trans 'All tickets' %}</a>
                    </div>
                </div>
            </div>
        </div>

        <div class="row mt-5">

            <div class="col-md-6 col-xs-12">
                <div class="card dark">
                    <div class="card-header">
                        {% trans 'Recent orders' %}
                    </div>

                    <div class="card-body">
                        <div class="table-responsive">
                            <table cellpadding="0" cellspacing="0" width="100%" class="table">
                                <tbody>
                                    {% for i, order in client.order_get_list({"per_page":5, "page":request.page, "hide_addons":1}).list %}
                                        <tr class="{{ cycle(['odd', 'even'], i) }}">
                                            <td><a href="{{ 'order/service/manage'|link }}/{{order.id}}">{{ order.title|truncate(30) }}</a></td>
                                            <td><span class="label {% if order.status == 'active'%}label-success{% elseif order.status == 'pending_setup' %}label-warning{% endif %}">{{ mf.status_name(order.status) }}</span></td>
                                        </tr>
                                    {% else %}
                                        <tr>
                                            <td colspan="3">{% trans 'The list is empty' %}</td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-6 col-xs-12">
                <div class="card dark">
                    <div class="card-header">
                        {% trans 'Recent emails' %}
                    </div>

                    <div class="card-body">
                        <div class="table-responsive">
                            <table cellpadding="0" cellspacing="0" width="100%" class="table">
                                <tbody>
                                    {% for i, email in client.email_get_list({"per_page":5}).list %}
                                        <tr class="{{ cycle(['odd', 'even'], i) }}">
                                            <td><a href="{{ 'email'|link }}/{{email.id}}">{{email.subject|truncate(30)}}</a></td>
                                            <td title="{{ email.created_at|bb_date }}">{{ email.created_at|timeago }} {% trans 'ago' %}</td>
                                        </tr>
                                    {% else %}
                                        <tr>
                                            <td colspan="2">{% trans 'The list is empty' %}</td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    {% endif %}
{% endblock %}