{% extends request.ajax ? "layout_blank.phtml" : "layout_default.phtml" %}

{% import "macro_functions.phtml" as mf %}

{% block meta_title %}{% trans 'Processing payment ...' %}{% endblock %}

{% block content %}
    <div class="row mt-5">
        <div class="col-md-12 text-center">
            <h1>{% trans 'Processing payment ...' %}</h1>
            <p>{% trans 'Thank you for your patience.' %}</p>
        </div>
    </div>

    <div class="row mt-5">
        <div class="col-md-4 ml-auto mr-auto">
            <div class="card dark">
                <div class="card-header">
                    {% trans 'Payment provider' %}
                </div>

                <div class="card-body">
                    {% if payment.type == 'html' %}
                        {{ payment.result|raw }}
                    {% endif %}

                    {% if payment.type == 'form' %}
                        <h2>{% trans 'Redirecting to payment gateway..' %}</h2>

                        <form name="payment_form" action="{{payment.service_url}}" method="post">
                            {% for key, value in payment.result %}
                                <input type="hidden" name="{{key}}" value="{{value}}" />
                            {% endfor %}
                            <input class="btn btn-info" type="submit" value="{% trans 'Please click here to continue if this page does not redirect automatically in 5 seconds' %}" id="payment_button"/>
                        </form>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script type="text/javascript">
        jQuery(document).ready(function(){
            document.getElementById('payment_button').style.display = 'none';
            document.forms["payment_form"].submit();
        });
    </script>
{% endblock %}