{% extends request.ajax ? "layout_blank.phtml" : "layout_default.phtml" %}
{% block meta_title %}{% trans 'Thank you' %}{% endblock %}
{% block breadcrumb %}<li class="active">{% trans 'Thank you' %}</li>{% endblock %}

{% block content %}
    <div class="row mt-5">
        <div class="col-md-12 text-center">
            <h1>{% trans 'Thank you' %}</h1>
            <p>{% trans%}Your payment is being processed right now. It can take up 5 minutes to complete.{% endtrans %}</p>
        </div>
    </div>

    <div class="row mt-5">
        <div class="col-md-4 ml-auto mr-auto">
            <div class="card dark">
                <div class="card-header">
                    {% trans %}Payment for invoice received{% endtrans %}
                </div>

                <div class="card-body">
                    <p>{% trans%}You will be automatically redirected to invoice page after 5 minutes.{% endtrans %}</p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script type="text/javascript">
        setTimeout(
            function(){
                CB.APP.Redirect("{{('/invoice/'~invoice.hash)|link }}");
            }, 5*60*1000
        );
    </script>
{% endblock %}