{% extends request.ajax ? "layout_blank.phtml" : "layout_default.phtml" %}
{% block meta_title %}{% trans 'Invoice management' %}{% endblock %}
{% block page_header %}{% trans 'Invoice management' %}{% endblock %}

{% block breadcrumb %}
    <li class="active">{% trans 'Invoices' %}</li>
{% endblock %}

{% block content %}

{% set unpaid_invoices = client.invoice_get_list({"status":"unpaid", "per_page":100}) %}
{% set paid_invoices = client.invoice_get_list({"per_page":10, "page":request.page, "status":"paid"}) %}

<div class="row mt-5">
    <div class="col-md-12 text-center">
        <h1>{% trans 'List of invoices' %}</h1>
        <p>{% trans 'All of your invoices can be found here. You can choose to see either paid or unpaid invoices by clicking corresponding button.' %}</p>
    </div>
</div>

<div class="row mt-5">
    <div class="col-md-6 col-xs-12 ml-auto mr-auto">
        <div class="card dark">
            <div class="card-header">
                {% trans 'List of invoices' %}
            </div>

            <div class="card-body">
                <nav>
                    <div class="nav nav-tabs" id="nav-tab" role="tablist">
                        <a class="nav-item nav-link active" id="nav-tab-invoices-unpaid" href="#nav-invoices-unpaid" data-toggle="tab" role="tab" aria-selected="true">{% trans 'Unpaid' %}</a>
                        <a class="nav-item nav-link" id="nav-tab-invoices-paid" href="#nav-invoices-paid" data-toggle="tab" role="tab" aria-selected="false">{% trans 'Paid' %}</a>
                    </div>
                </nav>
                <div class="tab-content" id="nav-tabContent">
                    <div class="tab-pane fade show active" id="nav-invoices-unpaid" role="tabpanel">
                        <div class="table-responsive">
                            <table cellpadding="0" cellspacing="0" width="100%" class="table">
                                <thead>
                                    <tr>
                                        <th>{% trans 'Title' %}</th>
                                        <th>{% trans 'Issue Date' %}</th>
                                        <th>{% trans 'Due Date' %}</th>
                                        <th>{% trans 'Total' %}</th>
                                        <th>&nbsp</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% if unpaid_invoices.total > 0 %}
                                        {% for i, invoice in unpaid_invoices.list %}
                                            <tr class="{{ cycle(['odd', 'even'], i) }}">
                                                <td>{{ "Proforma invoice #%05s"|format(invoice.id) }}</td>
                                                <td>{{ invoice.created_at|bb_date }}</td>
                                                <td>{{ invoice.due_at|bb_date }}</td>
                                                <td>{{ invoice.total | money(invoice.currency) }}</td>
                                                <td><a class="btn btn-small btn-info" href="{{ 'invoice'|link }}/{{ invoice.hash }}">{% trans 'Pay' %}</a></td>
                                            </tr>
                                        {% endfor %}
                                    {% else %}
                                        <tr>
                                            <td colspan="5" >{% trans 'The list is empty' %}</td>
                                        </tr>
                                    {% endif %}
                                </tbody>
                            </table>
                        </div>
                    </div>

                    <div class="tab-pane fade" id="nav-invoices-paid" role="tabpanel">
                        <div class="table-responsive">
                            <table cellpadding="0" cellspacing="0" width="100%" class="table">
                                <thead>
                                    <tr>
                                        <th>{% trans 'Title' %}</th>
                                        <th>{% trans 'Issue Date' %}</th>
                                        <th>{% trans 'Paid at' %}</th>
                                        <th>{% trans 'Total' %}</th>
                                        <th>&nbsp</th>
                                    </tr>
                                </thead>

                                <tbody>
                                    {% if paid_invoices.total > 0 %}
                                        {% for i, invoice in paid_invoices.list %}
                                            <tr class="{{ cycle(['odd', 'even'], i) }}">
                                                <td>{{ "Proforma invoice #%05s"|format(invoice.id) }}</td>
                                                <td>{{ invoice.created_at|bb_date }}</td>
                                                <td>{{ invoice.paid_at|bb_date }}</td>
                                                <td>{{ invoice.total | money(invoice.currency) }}</td>
                                                <td><a href="{{ 'invoice'|link }}/{{ invoice.hash }}" class="btn btn-info btn-small">{% trans 'View' %}</a></td>
                                            </tr>
                                        {% endfor %}
                                    {% else %}
                                        <tr>
                                            <td colspan="7">{% trans 'The list is empty' %}</td>
                                        </tr>
                                    {% endif %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

                <p class="mt-2">{{ unpaid_invoices.total }} unpaid invoices and {{ paid_invoices.total }} paid invoices</p>
            </div>
        </div>
    </div>
</div>

{% endblock %}

