{% import "macro_functions.phtml" as mf %}
{% set profile = admin.profile_get %}
{% set company = guest.system_company %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>{% block meta_title %}{% endblock %} - {{ company.name }}</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />

    <link rel="shortcut icon" href="favicon.ico" />

    {% include "partial_bb_meta.phtml" %}

    <link rel="stylesheet" href="css/main.css?v={{guest.system_version}}" type="text/css" media="screen" />

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <script type="text/javascript" src="js/boxbilling.min.js?v={{guest.system_version}}"></script>
    <script type="text/javascript" src="js/bb-admin.js?v={{guest.system_version}}"></script>

    {% block head %}{% endblock %}
</head>

<body>

{% if not admin %}
    <script type="text/javascript">$(function(){bb.redirect("{{ 'staff/login'|alink }}");});</script>
{% else %}

<header>
    <section class="wrapper">
        <div class="logo"><a href="{{ 'index'|alink }}" title="{{ company.name }}"><img src="images/logo_circlebilling.jpg" alt="{{ company.name }}"/></a></div>
        <nav class="topnav">

            <ul class="unstyled">

                <li class="dd">
                    <a class="new" title="{% trans 'New' %}"><span></span></a>
                    {% include "partial_menu_top.phtml" %}
                </li>

                <li>
                    <a class="home" href="{{ 'index'|alink }}" title="{% trans 'Dashboard' %}"><span></span></a>
                </li>

                {% if admin.system_is_allowed({"mod":"notification"}) and guest.extension_is_on({"mod":"notification"}) %}
                {% set count_notifications = admin.notification_get_list({"per_page":1}).total %}
                <li class="iMegaphone"><a href="{{ 'notification'|alink }}" title="{% trans 'Notifications' %}">{% trans 'Notifications' %}</a>{% if count_notifications %}<span class="numberMiddle">{{ count_notifications }}</span>{% endif %}</li>
                {% endif %}

                <li>
                    <a class="visit" href="{{ '/'|link }}" title="{% trans 'Visit site' %}" target="_blank"><span></span></a>
                </li>

                <li class="welcome">
                    <a class="user" href="{{ 'staff/profile'|alink }}" title="{{ profile.name }}"><span></span></a>
                </li>

                <li>
                    <a class="logout" href="{{ 'api/admin/profile/logout'|link }}" title="{% trans 'Logout' %}" class="api-link" data-api-redirect="{{ 'staff/login'|alink }}"><span></span></a>
                </li>

                <li class="loading" style="display:none;"><img src="images/loader.gif" alt="" /><span>{% trans 'Loading ...' %}</span></li>

            </ul>
        </nav>
        <div class="clear"></div>
    </section>
</header>

<main>
    {% if hide_menu %}

    {% block content_wide %}{% endblock %}

    {% else %}
    <div class="subnav">
        {% block left_top %}{% endblock %}
        {% block nav %}{% include "partial_menu.phtml" %}{% endblock %}
        {% block left_bottom %}{% endblock %}
    </div>

    {% block before_content %}{% endblock %}
    <div class="content">

        <div class="breadCrumbHolder module">
            <div class="breadCrumb module">
                {% block breadcrumbs %}
                <ul>
                    <li class="firstB"><a href="{{ '/'|alink }}">{% trans 'Home' %}</a></li>
                    <li class="lastB">{{ block('meta_title') }}</li>
                </ul>
                {% endblock %}
            </div>
        </div>

        {% block top_content %}{% endblock %}
        {% block content %}{% endblock %}
        <div class="clear"></div>
    </div>
    {% endif %}
</main>

<footer>
        {% include "partial_footer.phtml" with {'product': product} %}
</footer>

<div class="loading dim"></div>
    {% block js %}{% endblock %}
    <noscript id="noscript">
        <div class="msg error">
        NOTE: Many features on BoxBilling require Javascript and cookies. You can enable both via your browser's preference settings.
        </div>
    </noscript>
{% endif %}
</body>
</html>