<div class="mb10">
    <a href="http://docs.boxbilling.com/" title="" target="_blank">{% trans 'Help' %}</a>
    <a href="http://www.boxbilling.com/forum" title="" target="_blank">{% trans 'Forum' %}</a>
    <a href="https://github.com/boxbilling/boxbilling/issues" title="" target="_blank">{% trans 'Report bug' %}</a>
</div>
<div>
    &copy; {{ now|date('Y') }}. All rights reserved.
    <a href="http://www.boxbilling.com" title="Billing system" target="_blank">BoxBilling {{ guest.system_version }}</a>
</div>