{% extends "layout_public.phtml" %}

{% block meta_title %}{% trans 'Log in' %}{% endblock %}

{% block body_attributes %}class="signin"{% endblock %}

{% block body %}
    <form method="post" action="" class="form-signin">
        {% if settings.login_page_show_logo %}
            {% set company = guest.system_company %}
            {% if settings.login_page_show_logo %}
                <a href="{{ settings.login_page_logo_url | default('/')}}" target="_blank">
                    <img class="page-logo mb-4"  src="{{ guest.system_company.logo_url }}" alt="{{ guest.system_company.name }}" width="100%"/>
                </a>
            {% endif %}
        {% endif %}

        <label class="control-label" for="email">{% trans 'Email Address' %}</label>
        <input id="icon" type="text" class="form-control" placeholder="{% trans 'Your email address' %}" name="email" value="{{ request.email }}" required="required" data-validation-required-message="{% trans 'You must fill in your email.' %}" autofocus>

        <label class="control-label mt-4" for="password">{% trans 'Password' %}</label>
        <input id="password" type="password" class="form-control"  placeholder="{% trans 'Password' %}" name="password" required="required" value="{{ request.password }}" data-validation-required-message="{% trans 'You must fill in your password.' %}">

        {% if settings.login_page_show_remember_me %}
            <div class="checkbox mt-4">
                <label>
                    <input type="checkbox" value="remember-me" name="remember" checked="checked"> {% trans 'Remember me' %}
                </label>
            </div>
        {% endif %}

        <button class="btn btn-lg btn-dark btn-block mt-4" type="submit">{% trans 'Log in' %}</button>

        {% if settings.show_password_reset_link or settings.show_signup_link %}
        <p class="mt-4 text-center">
            {% if settings.show_signup_link%}
                <a href="{{ 'signup'|link }}"><small>{% trans 'Signup' %}</small></a> |
            {% endif %}

            {% if settings.show_password_reset_link%}
                <a href="{{ 'password-reset'|link }}"><small>{% trans 'Forgot password?' %}</small></a>
            {% endif %}
        </p>
        {% endif %}
    </form>
{% endblock%}

{% block js %}
    <script type="text/javascript">
        $(function() {
            $('#client-login').bind('submit',function(event){
                bb.post('guest/client/login',
                    $(this).serialize(),
                    function(result) {
                        bb.redirect();
                    }
                );
                return false;
            });
            {% if request.al %}
            $('#client-login').submit();
            {% endif %}
        });
    </script>
    <script src="{{ 'js/plugins/bootstrapValidation/jqBootstrapValidation.min.js' | asset_url}}"></script>
    <script>
        $(document).ready(function() {

            $("input").jqBootstrapValidation({
                submitSuccess: function($form, event) {
                    event.preventDefault();
                }
            });

        });
    </script>
{% endblock %}